Models/DersProgrami.cs
using System;
using System.Collections.Generic;

namespace Zeun.Web.Models;

public partial class DersProgrami
{
    public int DersProgramiId { get; set; }

    public int? DersAcmaId { get; set; }

    public int? DerslikId { get; set; }

    public int? DersGunuId { get; set; }

    public int? DersSaatiId { get; set; }

    public virtual DersAcma? DersAcma { get; set; }

    public virtual DersGunu? DersGunu { get; set; }

    public virtual DersSaati? DersSaati { get; set; }

    public virtual Derslik? Derslik { get; set; }
}

Models/Ogrenci.cs
using System;
using System.Collections.Generic;

namespace Zeun.Web.Models;

public partial class Ogrenci
{
    public int OgrenciId { get; set; }

    public int? BolumId { get; set; }

    public int? OgrenciDurumId { get; set; }

    public int? KullaniciId { get; set; }

    public string? OgrenciNo { get; set; }

    public DateTime? KayitTarihi { get; set; }

    public DateTime? AyrilmaTarihi { get; set; }

    public string? Adi { get; set; }

    public string? Soyadi { get; set; }

    public string? TckimlikNo { get; set; }

    public int? CinsiyetId { get; set; }

    public DateTime? DogumTarihi { get; set; }

    public string? Fotograf { get; set; }

    public string? Adres { get; set; }

    public string? Email { get; set; }

    public string? TelefonNumarasi { get; set; }

    public double? Gano { get; set; }

    public virtual Bolum? Bolum { get; set; }

    public virtual Cinsiyet? Cinsiyet { get; set; }

    public virtual ICollection<Danismanlik> Danismanliks { get; set; } = new List<Danismanlik>();

    public virtual ICollection<Degerlendirme> Degerlendirmes { get; set; } = new List<Degerlendirme>();

    public virtual ICollection<DersAlma> DersAlmas { get; set; } = new List<DersAlma>();

    public virtual Kullanici? Kullanici { get; set; }

    public virtual OgrenciDurum? OgrenciDurum { get; set; }
}

Controllers/OgrenciController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Rotativa.AspNetCore;
using Zeun.Web.Data;
using Zeun.Web.Models;

namespace Zeun.Web.Controllers
{
    public class OgrenciController : Controller
    {
        // dbcontext enjeksiyonu
        private readonly OgrenciDbContext _context;
        public OgrenciController(OgrenciDbContext context)
        {
            _context = context;
        }


        // Ogrenci indeksi
        public IActionResult Index()
        {   // loginde alınan ogrenciId ile verilerin getirilmesi
            int? ogrenciId = HttpContext.Session.GetInt32("ogrenciId");

            var ogrenci = _context.Ogrencis.FirstOrDefault(a => a.OgrenciId == ogrenciId);
            var bolum = _context.Bolums.FirstOrDefault(b => b.BolumId == ogrenci.BolumId);
            var mufredats = _context.Mufredats.Where(m => m.BolumId == bolum.BolumId).ToList();
            var akademikDonemList = new List<AkademikDonem>();


            //müfredattaki tüm dersleri dönme
            foreach (var mufredat in mufredats)
            {
                var akademikDonem = _context.AkademikDonems.Where(ad => ad.AkademikDonemId == mufredat.AkademikDonemId).ToList();
                akademikDonemList.AddRange(akademikDonem);
            }
                var viewModel = new OgrenciOzlukBilgileriViewModel()
            {
                Ogrenci = ogrenci,
                Bolum = bolum,
                Mufredat = mufredats,
                AkademikDonem = akademikDonemList,
                
            };





            return View("Index", viewModel);
        }



        // özlük Bilgilerini getiren action

        public IActionResult OzlukBilgileri()
        {
            int? ogrenciId = HttpContext.Session.GetInt32("ogrenciId");
            if (ogrenciId != null)
            {


                var ogrenci = _context.Ogrencis.FirstOrDefault(o => o.OgrenciId == ogrenciId);
                var bolum = _context.Bolums.FirstOrDefault(b => b.BolumId == ogrenci.BolumId);
                var ogrenciDurum = _context.OgrenciDurums.FirstOrDefault(od => od.OgrenciDurumId == ogrenci.OgrenciDurumId);



                var viewModel = new OgrenciOzlukBilgileriViewModel
                {
                    Ogrenci = ogrenci,
                    Bolum = bolum,
                    OgrenciDurum = ogrenciDurum,


                };

                return View("OzlukBilgileri", viewModel);
            }
            else
            {

                ViewBag.Error = "Öğrenci ID'si geçersiz";
                return View();
            }
        }



        // bölüm müfredatını getiren action

        public IActionResult BolumMufredati()
        {
            int? ogrenciId = HttpContext.Session.GetInt32("ogrenciId");

            if (ogrenciId != null)
            {


                var ogrenci = _context.Ogrencis.FirstOrDefault(o => o.OgrenciId == ogrenciId);
                var bolum = _context.Bolums.FirstOrDefault(b => b.BolumId == ogrenci.BolumId);
                var mufredats = _context.Mufredats.Where(m => m.BolumId == bolum.BolumId).ToList();
                var dersHavuzuList = new List<DersHavuzu>();
                var akademikYilList = new List<AkademikYil>();
                var dersTuruList = new List<DersTuru>();
                var dersDiliList = new List<DersDili>();

                foreach (var mufredat in mufredats)
                {
                    var akademikYil = _context.AkademikYils.Where(ad => ad.AkademikYilId == mufredat.AkademikYiIid).ToList();
                    akademikYilList.AddRange(akademikYil);

                    var dersHavuzu = _context.DersHavuzus.Where(d => d.DersId == mufredat.DersId).ToList();
                    dersHavuzuList.AddRange(dersHavuzu);
                }

                foreach (var ders in dersHavuzuList)
                {

                    var dersTuru = _context.DersTurus.FirstOrDefault(dt => dt.DersTuruId == ders.DersTuruId);
                    var dersDili = _context.DersDilis.FirstOrDefault(dd => dd.DersDiliId == ders.DersDiliId);


                    dersTuruList.Add(dersTuru);
                    dersDiliList.Add(dersDili);
                }


                // viewmodele ekleyerek biden çok tablo iletme
                var viewModel = new OgrenciOzlukBilgileriViewModel
                {
                    Ogrenci = ogrenci,
                    Bolum = bolum,
                    Mufredat = mufredats,
                    DersHavuzu = dersHavuzuList,
                    AkademikYil = akademikYilList,
                    DersTuru = dersTuruList,
                    DersDili = dersDiliList,



                };









                return View("BolumMufredati", viewModel);
            }
            else
            {
                //null durum işleme
                ViewBag.Error = "Öğrenci ID'si geçersiz";
                return View(); // hata mesajıyla view ı dönme
            }



        }


        // dönem derslerini getiren action
        public IActionResult DonemDersleri()
        {
            int? ogrenciId = HttpContext.Session.GetInt32("ogrenciId");


            // null kontrolü
            if (ogrenciId != null)
            {

                var ogrenci = _context.Ogrencis.FirstOrDefault(o => o.OgrenciId == ogrenciId);
                var bolum = _context.Bolums.FirstOrDefault(b => b.BolumId == ogrenci.BolumId);
                var mufredats = _context.Mufredats.Where(m => m.BolumId == bolum.BolumId).ToList();
                var dersHavuzuList = new List<DersHavuzu>();
                var dersAcmaList = new List<DersAcma>();
                var ogretimElemaniList = new List<OgretimElemani>();

                var dersTuruList = new List<DersTuru>();



                foreach (var mufredat in mufredats)
                {


                    var dersHavuzu = _context.DersHavuzus.Where(d => d.DersId == mufredat.DersId).ToList();
                    dersHavuzuList.AddRange(dersHavuzu);

                    var dersAcma = _context.DersAcmas.Where(da => da.MufredatId == mufredat.MufredatId);
                    dersAcmaList.AddRange(dersAcma);



                }

                foreach (var ders in dersHavuzuList)
                {

                    var dersTuru = _context.DersTurus.FirstOrDefault(dt => dt.DersTuruId == ders.DersTuruId);



                    dersTuruList.Add(dersTuru);

                }

                // tip hatası alınan kod veri çekmede çok sıkıntı yaşandı casting nedeni bulunamayan bir sebepten hata veriyor diğer tablolar vermezken 
                //foreach(var ders in dersAcmaList)
                //{
                //    var ogretimE = _context.OgretimElemanis.FirstOrDefault(d => d.OgretimElemaniId == ders.OgrElmId);

                //    ogretimElemaniList.Add(ogretimE);
                //}




                var viewModel = new OgrenciOzlukBilgileriViewModel
                {
                    Ogrenci = ogrenci,
                    Bolum = bolum,
                    Mufredat = mufredats,
                    DersHavuzu = dersHavuzuList,
                    DersTuru = dersTuruList,
                    DersAcma = dersAcmaList,







                };
                return View("DonemDersleri", viewModel);



            }
            return View();

        }



        //ders programını getiren action

        public IActionResult DersProgrami()
        {
            int? ogrenciId = HttpContext.Session.GetInt32("ogrenciId");


            if (ogrenciId != null)
            {

                var ogrenci = _context.Ogrencis.FirstOrDefault(o => o.OgrenciId == ogrenciId);
                var bolum = _context.Bolums.FirstOrDefault(b => b.BolumId == ogrenci.BolumId);
                var mufredats = _context.Mufredats.Where(m => m.BolumId == bolum.BolumId).ToList();
                var dersHavuzuList = new List<DersHavuzu>();
                var dersAcmaList = new List<DersAcma>();

                var dersTuruList = new List<DersTuru>();



                foreach (var mufredat in mufredats)
                {


                    var dersHavuzu = _context.DersHavuzus.Where(d => d.DersId == mufredat.DersId).ToList();
                    dersHavuzuList.AddRange(dersHavuzu);

                    var dersAcma = _context.DersAcmas.Where(da => da.MufredatId == mufredat.MufredatId);
                    dersAcmaList.AddRange(dersAcma);



                }

                foreach (var ders in dersHavuzuList)
                {

                    var dersTuru = _context.DersTurus.FirstOrDefault(dt => dt.DersTuruId == ders.DersTuruId);



                    dersTuruList.Add(dersTuru);

                }

                var DersProgrami = new List<DersProgrami>();
                foreach (var ders in dersAcmaList)
                {
                    var dersprogrami = _context.DersProgramis.Where(dp => dp.DersAcmaId == ders.DersAcmaId).ToList();
                    DersProgrami.AddRange(dersprogrami);

                }





                var viewModel = new OgrenciOzlukBilgileriViewModel
                {
                    Ogrenci = ogrenci,
                    Bolum = bolum,
                    Mufredat = mufredats,
                    DersHavuzu = dersHavuzuList,
                    DersTuru = dersTuruList,
                    DersAcma = dersAcmaList,
                    DersProgrami = DersProgrami,







                };
                return View("DersProgrami", viewModel);



            }
            return View();
        }


        // sınav notlarını getiren action
        public IActionResult SinavNotlari()
        {

Views/Ogrenci/BolumMufredati.cshtml
@model Zeun.Web.Models.OgrenciOzlukBilgileriViewModel
@{
    Layout = "~/Views/Shared/_OgrenciLayout.cshtml";
}



<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BolumMufredati</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css">

    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f8f9fa;
        }

        .card {
            margin-top: 20px;
        }

        .card-header {
            background-color: #7795aa;
            color: white;
        }

        .table-responsive {
            margin-top: 20px;
        }

        .table tbody tr:hover {
            background-color: #e0f7fa;
            cursor: pointer;
        }
    </style>
</head>

<body>
    
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Öğrenci Bölüm Müfredatı</h4>
                </div>
                <div class="card-content collapse show">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="akademikYil">Akademik Yıl:</label>
                            <select class="form-control" id="akademikYil">
                                @foreach (var akademikYil in Model.AkademikYil)
                                {
                                    <option>@akademikYil.AkademikYil1</option>
                                }
                            </select>
                        </div>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Ders Kodu</th>
                                        <th>Ders Adı</th>
                                        <th>Ders Türü</th>
                                        <th>Ders Dili</th>
                                        <th>Teorik (T)</th>
                                        <th>Uygulama (U)</th>
                                        <th>Dersin Dönemi</th>
                                        <th>Kredi (K)</th>
                                        <th>ECTS</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var ders in Model.DersHavuzu)
                                    {
                                      
                                        <tr>
                                            <td>@ders.DersKodu</td>
                                            <td>@ders.DersAdi</td>
                                            <td>@Model.DersTuru[Model.DersHavuzu.IndexOf(ders)].DersTuru1</td>
                                            <td>@Model.DersDili[Model.DersHavuzu.IndexOf(ders)].DersDili1</td>
                                            <td>@ders.Teorik</td>
                                            <td>@ders.Uygulama</td>
                                            <td>@Model.Mufredat[Model.DersHavuzu.IndexOf(ders)].DersDonemi</td>
                                            <td>@ders.Kredi</td>
                                            <td>@ders.Ects</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
</body>

Views/Ogrenci/DersKayit.cshtml
@model Zeun.Web.Models.OgrenciOzlukBilgileriViewModel
@{
    Layout = "~/Views/Shared/_OgrenciLayout.cshtml";
}




<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Öğrenci Ders Kayıt</title>
    <style>
        table {
            width: 80%;
            border-collapse: collapse;
            margin-top: 20px;
            margin-bottom: 40px;
        }

        th,
        td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 12px;
            font-size: 14px;
        }

        th {
            background-color: #7795aa;
        }

        .highlight {
            background-color: #e0f7fa;
            cursor: pointer;
        }

        .btn {
            padding: 8px 16px;
            cursor: pointer;
            color: white;
            border: none;
            border-radius: 4px;
        }

        .btn-primary {
            background-color: #598cde;
        }

        .btn-danger {
            background-color: #d36257;
        }

        .btn-success {
            background-color: #4b935e;
        }
    </style>
</head>

<body>

    <h2>Öğrenci Ders Kayıt</h2>

    <table>
        <thead>
            <tr class="highlight">
                <th>Ders Kodu</th>
                <th>Ders Adı</th>
                <th>Ders Türü</th>
                <th>Teorik (T)</th>
                <th>Uygulama (U)</th>
                <th>Kredi (K)</th>
                <th>ECTS</th>
                <th>İşlemler</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>101</td>
                <td>Veri Bilimi</td>
                <td>Zorunlu</td>
                <td>3</td>
                <td>2</td>
                <td>5</td>
                <td>6</td>
                <td>
                    <button class="btn btn-primary">Ders Ekle</button>
                    <button class="btn btn-danger">Ders Çıkar</button>
                    <button class="btn btn-success">Onayla</button>
                </td>
            </tr>
            <tr>
                <td>201</td>
                <td>Fizik</td>
                <td>Seçmeli</td>
                <td>2</td>
                <td>1</td>
                <td>4</td>
                <td>5</td>
                <td>
                    <button class="btn btn-primary">Ders Ekle</button>
                    <button class="btn btn-danger">Ders Çıkar</button>
                    <button class="btn btn-success">Onayla</button>
                </td>
            </tr>
        </tbody>
    </table>

</body>


Views/Ogrenci/DersProgrami.cshtml
@model Zeun.Web.Models.OgrenciOzlukBilgileriViewModel
@{
    Layout = "~/Views/Shared/_OgrenciLayout.cshtml";
}


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Yazılım Mühendisliği 2023-2024 Güz Ders Programı</title>
    <style>
        table {
            width: 80%;
            border-collapse: collapse;
            margin-top: 20px;
            margin-bottom: 40px;
        }

        th,
        td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 12px;
            font-size: 14px;
        }

        th {
            background-color: #f2f2f2;
        }

        .highlight {
            background-color: #e6f7ff;
            text-align: center;
        }
    </style>
</head>

<body>



    <table>
        <tr>
            <th>Saat</th>
            <th>Pazartesi</th>
            <th>Salı</th>
            <th>Çarşamba</th>
            <th>Perşembe</th>
            <th>Cuma</th>

        </tr>
        @foreach(var dersSaat in Model.DersProgrami){
        <tr>
            <td class="highlight">@dersSaat.DersSaati</td>
            <td>@Model.DersHavuzu</td>
            <td>BOŞ</td>
            <td>BOŞ</td>
            <td>BOŞ</td>
            <td class="highlight">YMM4143<br>Makine Öğrenmesi<br>Dr. Öğr. Üyesi Buket TOPTAŞ<br>6 Nolu Derslik</td>
        </tr>
        }
    </table>

</body>

</html>

Views/Ogrenci/DonemDersleri.cshtml
@model Zeun.Web.Models.OgrenciOzlukBilgileriViewModel
@{
    Layout = "~/Views/Shared/_OgrenciLayout.cshtml";
}


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Öğrenci Dönem Dersleri</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css">
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f8f9fa;
        }

        .card {
            margin-top: 20px;
        }

        .card-header {
            background-color: #7795aa;
            color: white;
        }

        .table-responsive {
            margin-top: 20px;
        }

        .table tbody tr:hover {
            background-color: #e0f7fa;
            cursor: pointer;
        }
    </style>
</head>

<body>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Öğrenci Dönem Dersleri</h4>
                </div>
                <div class="card-content collapse show">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Ders Kodu</th>
                                        <th>Ders Adı</th>
                                        <th>Ders Türü</th>
                                        <th>Ders Sorumlusu</th>
                                        <th>Teorik (T)</th>
                                        <th>Uygulama (U)</th>
                                        <th>Kredi (K)</th>
                                        <th>ECTS</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var ders in Model.DersHavuzu)
                                    {

                                    
                                    <tr>
                                     
                                        <td>@ders.DersKodu</td>
                                        <td>@ders.DersAdi</td>
                                            <td>@Model.DersTuru[Model.DersHavuzu.IndexOf(ders)].DersTuru1</td>
                                        <td>Doç.Dr. Abdullah Elen</td>
                                        <td>@ders.Teorik</td>
                                        <td>@ders.Uygulama</td>
                                        <td>@ders.Kredi</td>
                                        <td>@ders.Ects</td>
                                    </tr>

                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
</body>


Views/Ogrenci/Index.cshtml
@model Zeun.Web.Models.OgrenciOzlukBilgileriViewModel

@{
    Layout = "/Views/Shared/_OgrenciLayout.cshtml";
}

<body>
    <div class="container mt-5">
        <div class="container mt-5">
            <div class="row">
                <div class="col-md-3">
                    <div class="box box-1">
                        <h5>Aktif Akademik Dönem Bilgileri</h5>
                        <p>2023-2024 Güz Dönemi  </p>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="box box-2">
                        <h5>Danışman Bilgileri</h5>
                        <p>Arş. gör. Maide Feyza Er</p>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="box box-3">
                        <h5>Öğrenim Bilgileri</h5>
                        <p>@Model.Bolum.BolumAdi</p>
                        <p>4. Sınıf</p>
                        <p>@Model.Ogrenci.KayitTarihi</p>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="box box-4">
                        <h5>GANO</h5>
                        <p></p>
                        <p>2,42</p>
                    </div>
                </div>
            </div>
        </div>
    </div>


</body>


Views/Ogrenci/SinavNotlari.cshtml
@model Zeun.Web.Models.OgrenciOzlukBilgileriViewModel
@{
    Layout = "~/Views/Shared/_OgrenciLayout.cshtml";
}



<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Öğrenci Sınav Sonuçları</title>
    <style>
        table {
            width: 80%;
            border-collapse: collapse;
            margin-top: 20px;
            margin-bottom: 40px;
        }

        th,
        td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 12px;
            font-size: 14px;
        }

        th {
            background-color: #7795aa;
        }

        .highlight {
            background-color: #e0f7fa;
            text-align: center;
        }

        tr:hover {
            background-color: #e0f7fa;
            cursor: pointer;
        }
    </style>
</head>

<body>

    <h2>Öğrenci Sınav Sonuçları</h2>

    <table>
        <thead>
            <tr class="highlight">
                <th>Ders Kodu</th>
                <th>Ders Adı</th>
                <th>Sınav Türü</th>
                <th>Sınav Etki Oranı</th>
                <th>Sınav Notu</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var sinav in Model.Sinav)
            {
                <tr>
                    <td>@Model.DersHavuzu[Model.Sinav.IndexOf(sinav)].DersKodu</td>
                    <td>@Model.DersHavuzu[Model.Sinav.IndexOf(sinav)].DersAdi</td>
                    <td>@Model.SinavTuru[Model.Sinav.IndexOf(sinav)].SinavTuru1</td>
                    <td>@sinav.EtkiOrani</td>
                    <td>@Model.Degerlendirme[Model.Sinav.IndexOf(sinav)].SinavNotu</td>
                </tr>
            }
        </tbody>
    </table>

</body>

</html>

Views/Ogrenci/Transkript.cshtml
@model Zeun.Web.Models.OgrenciOzlukBilgileriViewModel
@{
    Layout = "~/Views/Shared/_OgrenciLayout.cshtml";
}
@functions {

   
}




<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Bandırma OnYedi Eylül Üniversitesi - Öğrenci Transkripti</title>
    <style>
        .table-container {
            display: flex;
            flex-wrap: wrap;
        }

            .table-container table {
                width: 45%;
                margin-right: 5%;
                float: left;
                margin-bottom: 20px;
            }

        th,
        td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }

        body {
            font-family: "Arial", sans-serif;
            margin: 20px;
        }

        h1,
        h2 {
            text-align: center;
            color: #333;
        }

        #bilgiKutulari {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
        }

        #ogrenciBilgileri,
        #kurumsalBilgiler {
            width: 48%;
            padding: 10px;
            border: 1px solid #1e1c1c;
            border-radius: 7px;
        }

        #genelBilgiler {
            width: 100%;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 5px;
        }
    </style>
</head>

<body>
    <h1>Bandırma OnYedi Eylül Üniversitesi - Öğrenci Transkripti</h1>

    <div id="bilgiKutulari">
        <div id="ogrenciBilgileri">
            <h2>Öğrenci Bilgileri</h2>
            <p><strong>Adı Soyadı:</strong> @Model.Ogrenci.Adi  @Model.Ogrenci.Soyadi</p>
            <p><strong>T.C. Kimlik No:</strong> @Model.Ogrenci.TckimlikNo</p>
            <p><strong>Öğrenci No:</strong> @Model.Ogrenci.OgrenciNo</p>
            <p><strong>Bölüm / Program:</strong> @Model.Bolum.BolumAdi</p>
        </div>

        <div id="kurumsalBilgiler">
            <h2>Kurumsal Bilgiler</h2>
            <p><strong>Tarih:</strong> @DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")</p>
            <p><strong>Kayıt Tarihi:</strong> @Model.Ogrenci.KayitTarihi</p>
            <p><strong>Ayrılış Tarihi:</strong> @Model.Ogrenci.AyrilmaTarihi</p>
            <p>
                <strong>Top.Krd/AGNO:</strong> @foreach (var kredi in Model.DersHavuzu)
                {
                    kredi.Kredi += kredi.Kredi;
                    @kredi.Kredi
                }
                / @Model.Ogrenci.Gano
            </p>
            <p><strong>Öğrenim Durumu:</strong>@Model.OgrenciDurum.OgrenciDurumu</p>
        </div>
    </div>

    <div class="table-container">
        @for (int donem = 1; donem <= 8; donem++)
        {
            <table>
                <caption>@donem. Sınıf @((donem % 2 == 1) ? "Güz" : "Bahar") Dönemi</caption>
                <thead>
                    <tr>
                        <th>Ders Kodu ve Adı</th>
                        <th>Ders Türü</th>
                        <th>Teorik</th>
                        <th>Uygulama</th>
                        <th>Kredi</th>
                        <th>ECTS</th>
                        <th>Dörtlük Not</th>
                        <th>Harf Notu</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var ders in Model.DersHavuzu)
                    {
                        <tr>
                            <td>@ders.DersKodu - @ders.DersAdi</td>
                            <td>@Model.DersTuru[Model.DersHavuzu.IndexOf(ders)].DersTuru1</td>
                            <td>@ders.Teorik</td>
                            <td>@ders.Uygulama</td>
                            <td>@ders.Kredi</td>
                            <td>@ders.Ects</td>
                            <td>[Not]</td>
                            <td>[Harf Notu]</td>
                        </tr>
                    }
                    <tr>
                        <td colspan="8" style="text-align: right">
                            Genel Akademik Not Ortalaması (GANO): 222222
                        </td>
                    </tr>
                </tbody>
            </table>
        }



      
        

    </div>
    <button class="alert-info md-3"><a href="@Url.Action("IndirTranskriptPDF", "Ogrenci")">PDF İndir</a></button>

</body>
</html>